faahjaelp/faahjaelp/urls.py
# -*- coding: utf-8 -*-  
from django.conf.urls import patterns, include, url
from django.contrib import admin
from faahjaelp import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
admin.autodiscover()                                    #used admin.autodiscover() to automatically load the INSTALLED_APPS admin.py modules

urlpatterns = patterns('customer.views',    #avoid redundancy                     
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^logout/$', 'userLogout'),
    (r'^admin/', include(admin.site.urls)),    
    (r'^register/$','register'),                          # can also import the view module and add the method here instead of a string
     (r'^login/$','userLogin'),
    (r'^login/(?P<jobid>.*)/$','userLogin'),
    (r'^profile/$','profile'),
    (r'^hjaelp/$','help'),
    (r'edit/(?P<slug>.*)/$', 'edit'),
    (r'edit_pic/(?P<slug>.*)/$', 'edit_pic'),
    (r'^arbejder/(?P<worker_type>[\w|\W]+)/$', 'worker'),
    (r'^arbejder/$', 'worker'),
    (r'^arbejder/bruger/(?P<slug>.*)/$', 'specificUser'),
    
    

)+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns+= patterns('job.views', 
     url(r'^$', 'index'), 
     (r'^profile/addJob/$', 'addJob'),
     (r'editjob/(?P<jobid>.*)/$', 'editJob'),
     (r'^jobvalg/(?P<jobid>.*)/$','jobValg'),
    (r'^job/(?P<jobtype>[\w|\W]+)/$', 'index'),        # allow space in url, ^(?P<jobtype>\w+)/ wont take space
    )

urlpatterns+= patterns('',
    (r'^resetpassword/$', 'django.contrib.auth.views.password_reset'),
    (r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm'),
    (r'^resetpassword/passwordsent/$', 'django.contrib.auth.views.password_reset_done'),
    (r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete'),
)
urlpatterns+=staticfiles_urlpatterns() 

faahjaelp/customer/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
   
class Comment(models.Model):
    fromCustomer=models.ForeignKey('Customer')
    toCustomer=models.ForeignKey('Customer', related_name='comment_to_customer')
    comment=models.TextField()
    time=models.DateTimeField()
    class meta:
        ordering=['toCustomer']
        


class Customer(User):                                                      # i was try to make a customer table before without dependent to User table
    slug=models.SlugField(unique=True)
    description=models.TextField(null=True)
    phone=models.IntegerField(null=True)
    id_verified=models.NullBooleanField()
    picture=models.ImageField(upload_to='media/customer', null=True)
    isWorker=models.BooleanField()
    genre=models.ManyToManyField('job.JobGenre', through='WorkerGenre',null=True )
    

    
    def save(self,*args,**kwargs):                                         #override save method, 
        self.slug=slugify(self.username)                                   #method slugify() Converts to lowercase, removes non-word characters (alphanumerics and underscores) and converts spaces to hyphens. Also strips leading and trailing whitespace.
        super(Customer,self).save(*args, **kwargs)                         #edit username can cause broken links, 
    
    def __unicode__(self):
        return self.username
    

        
    
class WorkerGenre(models.Model):
    worker=models.ForeignKey(Customer)
    genre=models.ForeignKey('job.JobGenre')    

faahjaelp/job/models.py
from django.db import models
from customer.models import Customer

class JobGenre(models.Model):
    genre=models.CharField(max_length=40) # max_length is the required argument
    def __unicode__(self):
        return self.genre
    
class Image(models.Model):
    toJob=models.ForeignKey('Job', verbose_name=' images to the job with id') # foreign key, represent many to one relationship,  use a class that havn't been defined
    image=models.ImageField(upload_to='media/job')
    
class Question(models.Model):
    toJob=models.ForeignKey('Job', verbose_name='questions to the job with id')
    question=models.TextField()
    answer=models.TextField()
    
    class Meta:
        ordering=["toJob"]
        
    

class Job(models.Model):
    title=models.CharField(max_length=40)
    genre=models.ManyToManyField(JobGenre, through='GenreToJob')   # many to many relation, a job can have many genre and a genre can give to many jobs
    creator=models.ForeignKey(Customer)
    location=models.TextField()
    start_time=models.DateTimeField()             
    end_time=models.DateTimeField()
    description=models.TextField()
    reward=models.CharField(max_length=100, null=True)
    isActive=models.BooleanField(default=True)
    picture=models.ImageField(upload_to='media/job', null=True)     
    questions=models.ForeignKey(Question,null=True )
    
    def __unicode__(self):
        return self.title
    
    class Meta:
        ordering=['-end_time','creator']
        
class GenreToJob(models.Model):
    job=models.ForeignKey(Job)
    genre=models.ForeignKey(JobGenre)
        
#class PassJob(models.Model):                                       # cannot overwrite a field in Django, 
#    id_for_job= models.IntegerField(primary_key=True)
#    title=models.CharField(max_length=40)
#    genre=models.ManyToManyField(JobGenre)   
#    creator=models.ForeignKey(Customer)
#    location=models.TextField()
#    start_time=models.DateTimeField()             
#    end_time=models.DateTimeField()
#    description=models.TextField()
#    reward=models.TextField(null=True)
#    
#    class meta:
#        ordering=['end_time']
#        
#    def __unicode__(self):
#        return self.title
#    
    

    
    
    
    

faahjaelp/job/forms.py
# -*- coding: utf-8 -*-   
from django.forms.models import ModelForm
from job.models import Job
from django import forms
from faahjaelp import settings
import imghdr
class CreateJob(ModelForm):    
    start_time=forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M'])
    end_time=forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M'])
    picture=forms.FileField(required=False)
    
    def clean_picture(self):
        picture=self.cleaned_data['picture']
        if picture is not None:
            print picture
            if imghdr.what(picture):
                if  picture.size> settings.MAX_PIC_SIZE:
                    raise forms.ValidationError('Billedet er for stor, max størrelse på billede er  '+str(settings.MAX_PIC_SIZE)+"bit")
                else:
                    return picture
            else:
                    raise forms.ValidationError(' det er ikke et billede file')
        else:
            return None

    class Meta:
        model=Job
        exclude=('creator','questions')

faahjaelp/templates/addJob.html
{%extends "base.html" %}

{% block title %}
Tilføj job
{% endblock %}

{% block content %}
<div class="form">
	<form action="" method="post" enctype="multipart/form-data" >
	{% csrf_token %} 

		Brugnavn: {{customer.username}} </br>
		{{text}}
		
		{% if form.title.errors %}  <div class="error">{{form.title.errors}}</div>  {%endif%}
		<p><label for="title" >Title:  </label>{{ form.title}} <p>
		
		{% if form.genre.errors %}  <div class="error">{{form.genre.errorss}}</div>  {%endif%}
		<p><label for="genre">Type:</label></p>
		<p>Hold "Ctrl" (eller "Æbletasten" på Mac) nede for at vælge mere end en</p>
		 <P>{{form.genre}}  </p>
		
		{% if form.location.errors %}  <div class="error">{{form.location.errors}}</div>  {%endif%}
		<p><label for="location" >Addresse:  </label></p><p>{{ form.location}} </p>
		
		{% if form.start_time.errors %}  <div class="error">{{form.start_time.error}}</div>  {%endif%}
		<p><label for="start_time">Start tid:</label> {{form.start_time}} åååå-mm-dd tt:mm</p>
		
		{% if form.end_time.errors %}  <div class="error">{{form.end_time.error}}</div>  {%endif%}
		<p><label for="end_time">Slutt tid:</label> {{form.end_time}} åååå-mm-dd tt:mm</p>
		
		{% if form.description.errors %}  <div class="error">Beskiver jobbet:</div>  {%endif%}
		<p><label for="description">Beskirv jobbet:</label></p> <p> {{form.description}}</p>
		
		<p><label for="reward">Skriv hvad vil du tilbyde personen som udfører jobbet, det behøver ikke at være penge</label> {{form.reward}}</p>
		
		{% if form.isActive.errors %}  <div class="error"> Sæt flueben her</div>{%endif%}
		<p><label for="isActive">Aktiver et job, så brugerne kan se det:</label> {{form.isActive}}</p>
	
		{% if form.picture.errors %}  <div class="error">vælg et gyldigt billede  </div>{%endif%}
		<p><label for="id_picture">Billede:</label>{{form.picture}}</p>
		
		{% if form.errors %} <div class="error">{{form.errors}} Vær at venlig indtaste korrekt information</div> {%endif%} 
		  
		<p><input type="submit"  value="Tilføj"></p>
		</form>
		<div class='note'>{{text}}</div>
{% endblock%}

faahjaelp/templates/arbejder.html
{% extends "base.html" %}
{% block typemenu %}
	   <ul id="nav">
        	<li><a href="/arbejder/"> dem der tilbyder hjælper</a></li>
	        {% for j in all_job_genres %}
	        	<li><a href= "/arbejder/{{j.genre}}/">{{j.genre}}</a></li>
	        {% endfor %}
	     </ul>
{% endblock %}

{% block content %}

<table >
<tr>
	<th>Hvem</th>
	<th>selv deskrivelse</th>
</tr>	
{% for w in worker %}
 <tr>
   		<td><a href="/arbejder/bruger/{{w.slug}}">{{w.username}}</a></td>
	    <td>{% for  g in w.genre.all %} {{g}} {% endfor %} </td>
 </tr>
{% endfor %}
</table>
{% endblock%}

faahjaelp/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>
{% block title %}
Untitled Document
{% endblock %}
</title>
<link href="{{STATIC_URL}}style.css" rel="stylesheet" type="text/css" />
<!-- <link href="C:/Users/hl/workspace/faahjaelp/static/style.css" rel="stylesheet" type="text/css" />-->
</head>

<body>
<div class="all">
 	<div class="headerOne">
    </div>
	<div class="con">
        <div class="headTwo"><h1>FåHjælp.dk </h1></div>
        <div class="menu">
        <a href='/'> Velkommen &nbsp;&nbsp;</a>   <a href="/hjaelp/"> Hjælp &nbsp;&nbsp;</a>
		{% if user.is_authenticated %}<a href="/profile/">Profil &nbsp;&nbsp;</a><a href="/logout/"> Log ud &nbsp;&nbsp;</a> 
			<a href="/profile/addJob/">  Tilføjl et nyt job &nbsp;&nbsp;</a>
			
		{%else%} <a href='/login/'> Login &nbsp;&nbsp;</a> 
		<a href='/register/'> Registrer &nbsp;&nbsp;</a>
		{% endif %}
		<a href="/arbejder/" style="float: right;"> Dem som vil hjælpe dig</a>
		</div>
		{% block typemenu %}
        <div class="jobtype">
        <ul id="nav">
        	<li><a href="/"> Job til alle</a></li>
	        {% for j in all_job_genres %}
	        	<li><a href= "/job/{{j.genre}}/">{{j.genre}}</a></li>
	        {% endfor %}
	     </ul>
        </div>
        {% endblock %}
	
        <div class="rigthside">
        </div>
  <div class="leftside">		
{% block content %}	
        
{% endblock %}
</div>
        <div class="button"> @ Copyright 2013 beta version</div>
	</div>
</div>
</body>
</html>

faahjaelp/templates/edit.html
{%extends "base.html" %}

{% block title %}
Ændre din profil
{% endblock %}

{% block content %}
Ændre dine oplysninger her:
<div class="form">
	<form action="" method="post" enctype="multipart/form-data" >
	{% csrf_token %} 

		Brugnavn: {{customer.username}} {{text}}
		
		{% if form.first_name.errors %}  <div class="error">{{form.first_name.errors}}</div>  {%endif%}
		<p><label for="first_name" >Fornavn:  </label>{{ form.first_name}} <p>
		
		{% if form.last_name.errors %}  <div class="error">{{form.last_name.errors}}</div>  {%endif%}
		<p><label for="last_name" >Efternavn:  </label>{{ form.last_name}} <p>
		
		{% if form.password.errors %}  <div class="error">skriv en gyldig password</div>  {%endif%}
		<p><label for="password">Password:</label> {{form.password}} </p>
		
		{% if form.password2.errors %}  <div class="error">to password er ikke ens</div>  {%endif%}
		<p><label for="id_password2">Gentast password:</label> {{form.password2}}</p>
		
		{% if form.email.errors %}  <div class="error">skriv en gyldig email</div>  {%endif%}
		<p><label for="id_email">Email:</label> {{form.email}}</p>
		
		<p><label for="id_description">Beskriv lidt om dig selv:</label></p>
		<p> {{form.description}}</textarea></p>
		
		{% if form.phone.errors %}  <div class="error">indtast et gyldigt telefon nummer  </div>{%endif%}
		<p><label for="id_phone">Phone:</label>{{form.phone}}</p>
		
		{% if form.picture.errors %}  <div class="error">vælg et gyldigt billede  </div>{%endif%}
		<p><label for="id_picture">Picture:</label>{{form.picture}}</p>
		
		{% if form.isWorker.errors %}  <div class="error"> sæt flueben her</div>{%endif%}
		<p><label for="id_isWorker">Vil du registere dig self som en der tilbyder både arbjeder og arbjedstjenest:</label> {{form.isWorker}}</p> 
		
		{% if form.keyword.errors %}  <div class="error"> {{form.keyword.errors}}</div>{%endif%}
		<label for="keyword"> Hvis du leder efter job, så kan du vælge hvilken jobtype du leder efter</label></br>
		 Hold "Ctrl" (eller "Æbletasten" på Mac) nede for at vælge mere end en</br>
		{{form.keyword}}
		{% if form.errors %} <div class="error">{{form.errors}} vær at venlig indtaste korrekt information</div> {%endif%} 
		  
		<p><input type="submit" alt="Ændre", value="Ændre"></p>
		</form>
{% endblock %}

faahjaelp/templates/editjob.html
{% extends "base.html"%}
{% block title%}
 {{text}}
 {% endblock %}
 {% block content %} 
<div class="form">
	<form action="" method="post" enctype="multipart/form-data" >
	{% csrf_token %} 
		{% if form.title.errors %}  <div class="error">{{form.title.errors}}</div>  {%endif%}
		<p><label for="title" >Overskrift:</label> {{form.title}}</p>
		
		{% if form.genre.errors %}  <div class="error">{{form.genre.errorss}}</div>  {%endif%}
		<p><label for="genre">Type:</label> {{form.genre}}  Hold "Ctrl" (eller "Æbletasten" på Mac) nede for at vælge mere end en.</p>
		
		{% if form.location.errors %}  <div class="error">Skriv en addresse</div>  {%endif%}
		<p><label for="location">Addresse:</label> </p><p>{{form.location}}</p>
		
		{% if form.start_time.errors %}  <div class="error">{{form.start_time.error}}</div>  {%endif%}
		<p><label for="start_time">Start tid:</label> {{form.start_time}} åååå-mm-dd tt:mm</p>
		
		{% if form.end_time.errors %}  <div class="error">{{form.end_time.error}}</div>  {%endif%}
		<p><label for="end_time">Slutt tid:</label> {{form.end_time}} åååå-mm-dd tt:mm</p>
		
		{% if form.reward.errors %}  <div class="error">Skriv hvad du vil tilbyde personen som udfører jobbet, det behøver ikke at være penge</div>  {%endif%}
		<p><label for="reward">skriv hvad vil du give for person som udfører jobbet, det behøver ikke at være penge:</label>{{form.reward}}</p>
		
		{% if form.description.errors %}  <div class="error"> Mangler beskrivelse</div>{%endif%}
		<p><label for="description">Beskriv jobbet</label></br> {{form.description}}</p> 
		
		{% if form.isActive.errors %}  <div class="error"> Sæt flueben her</div>{%endif%}
		<p><label for="isAtive">Aktiver jobbet, så brugerne kan se det:</label> {{form.isActive}}</p> 	
		
		{% if form.picture.errors %}  <div class="error">vælg et gyldigt billede  </div>{%endif%}
		<p><label for="id_picture">Billede:</label>{{form.picture}}</p>		
		
		{% if form.errors %} <div class="error">{{form.errors}} Vær at venlig at indtaste korrekt information</div> {%endif%}
		
	<input type="submit" name="change" value='Ændre'>
	<input type="submit" name="delete" value='Slet jobbet'>
	</form>
</div>
{% endblock %}

faahjaelp/templates/editpic.html
{% extends 'base.html' %}

{% block title %}
ændre dit profil billede her 
{% endblock %}

{% block content %}


{{text}}
 <form action="" method="post" enctype="multipart/form-data" >
 	{% csrf_token %} 
 	dit nuværrende profile billede er: 
		{% if not customer.picture %}
			Du har ikke noget profile billede.
		{% else%}
			<img src="{{MEDIA_URL}}{{customer.picture}}" width="200" height="150">
		
		{% endif %}
 		{% if form.picture.errors %}  <div class="error">vælg et gyldigt billede  </div>{%endif%}
		<p><label for="id_picture">Picture:</label>{{form.picture}}</p>
	<input type="submit" name="delete" value="Slet" />
	<input type="submit" name="change" value="Ændre" />
	{{ form.errors }}
</form>

{% endblock %}

faahjaelp/templates/hjælp.html
{% extends "base.html" %}
{% block title %}
Hjælp
{% endblock%}
{% block content %}
Hey, du kan skrive eller ringe til os , hvis du har brug for hjælp 
{% endblock %}

faahjaelp/templates/index.html
{%extends "base.html" %}

{% block title %}
velkom til Fåhjælp.dk
{% endblock %}

{% block content %} 
<h1>Tilgængelige job  lige nu {% if jobtype %}i {{jobtype}} {% endif %}</h1>
<table >
<tr>
	<th>Tjeneste</th>
	<th>Operatør</th>
	<th>Start tid</th>
	<th>Slut tid</th>
</tr>	
{% for job in jobs %}
 <tr>
   		<td><a href="/jobvalg/{{job.id}}/">{{job.title}}</a></td>
	    <td>{{job.creator}}</td>
	    <td>{{job.start_time}}</td>
	    <td>{{job.end_time}}</td>
  </tr>
{% endfor %}
</table>

{% endblock %}


faahjaelp/templates/jobvalg.html
{% extends "base.html" %}

{% block title %}
{{job.title}}
{% endblock %}

{% block content %}

<table>
<tr>
	<th>Title</th><th>Operatør</th><th>Address</th><th>Startid</th><th>Sluttid</th><th>beskivelse</th><th>belønning</th><th>Kontakt info</th>
</tr>
<tr>
	<td>{{job.title}}</td><td>{{job.creator}}</td><td>{{job.location}}</td><td>{{job.start_time}}</td>
	<td>{{job.end_time}}</td><td>{{job.description}}</td><td>{{job.reward}}</td>
	{% if user.is_authenticated %} <td>{{customer.email}}</br>Tlf:{{customer.phone}}</td>
</tr>
		{% if not job.picture %}{% else%}
		 <img src=" {{MEDIA_URL}}{{job.picture}}" width="250" height="250">
	 	{%endif %} 
	{% else %} <td><a href="/login/{{job.id}}"> Log in her for at se kontakt information</a></td></tr>
	{% endif %}

</table>
{% endblock %}

faahjaelp/templates/login.html

{% extends "base.html"%}
{% block title %}
login
{% endblock %}
{%block content %}
Log ind på din konto her:
<h3>{{text}}</h3>
<div class="form">
<form action="" method="post">
{% csrf_token%}
	
	 {% if form.username.errors%}<div class="error">{{form.username.errors}}</div> {% endif%}
	<p><label for="username"}>Brugernavn: </label>{{form.username}}</p>
	
	 {% if form.password.errors%}<div class="error"> {{form.password.errors}}</div> {% endif%}
	<p><label for="password">Password: </label>{{form.password}}</p>
	
	<p>Glemt dit kodeord? <a href= "/resetpassword/">Tryk her</a></p>
	
	<input type="submit" value="Login">
</form>
</div>

{% endblock %}

faahjaelp/templates/person.html
{% extends 'base.html' %}

{% block content %}
{% if not worker.picture %}{% else%}
		 <img src=" {{MEDIA_URL}}{{worker.picture}}" width="250" height="250">
{%endif %} 

	<table>
	<tr>
		<th>Brugnavn</th><th>fornavn</th><th>Efternavn</th><th>selv-beskrivelse</th><th>Type</th><th>Kontakt info</th>
	</tr>
	<tr>
		<td>{{worker.username}}</td><td>{{worker.first_name}}</td><td>{{worker.last_name}}</td><td>{{worker.description}}</td>
		<td>{% for g in worker.genre.all %} {{g}} {% endfor %}</td>
		{% if user.is_authenticated %} <td>{{worker.email}}</br>Tlf:{{worker.phone}}</td>
		</tr>
		{% else %} <td><a href="/login/{{job.id}}"> Log in her for at se kontakt information</a></td></tr>
		{% endif %}
	
	</table>
{% endblock %}

faahjaelp/templates/profile.html
{% extends "base.html"%}

{% block title %}
{{customer.username}}
{% endblock %}

{% block content %}
<h2>Hey, {{customer.username}}</h2>

{{customer.email}}

{% if not customer.picture %}
{% else%}
<img src="{{MEDIA_URL}}{{customer.picture}}" width="200" height="150">

{% endif %}
</br>
	<a href="edit/{{customer.slug}}/"> Rediger din profil her</a></Br>
	<a href="edit_pic/{{customer.slug}}/"> Rediger dit profil billede her</a> </br>
	<a href="/profile/addJob/">  Tilføjle et nyt job    </a></br>
		<h4>Rediger job som du tibyder:</h4>
		{% for j in job %}
		 <a href="editjob/{{j.id}}/"> {{j.title}}</a></br>
		 {% endfor %}
	 
 {% endblock %}
</body>
</html>

faahjaelp/templates/register.html
{% extends "base.html" %}
{% block title %} Register {% endblock%}
{% block content %}
<div class="form">
	<form action="" method="post">
	{% csrf_token %} <!-- it is a secrete user side specified token in all form submission and side-effect URLs to prevent cross site request forgeries -->
	<!--  we can use form.as_p here but the field names will be in English and there will be only one password field. adn password is viewable.-->
		{% if form.username.errors %}  <div class="error">{{form.username.errors}}</div>  {%endif%}
		<p><label for="username" >Brugnavn:</label> {{form.username}}</p>
		
		{% if form.password.errors %}  <div class="error">skriv en gyldig password</div>  {%endif%}
		<p><label for="password">Password:</label> {{form.password}} </p>
		
		{% if form.password2.errors %}  <div class="error">to password er ikke ens</div>  {%endif%}
		<p><label for="id_password2">Gentast password:</label> {{form.password2}}</p>
		
		{% if form.email.errors %}  <div class="error">skriv en gyldig email</div>  {%endif%}
		<p><label for="id_email">Email:</label> {{form.email}}</p>
		
		<p><label for="id_description">Beskriv lidt om dig selv:</label></p>
		<p> {{form.description}}</textarea></p>
		
		{% if form.phone.errors %}  <div class="error">indtast et gyldig telefon nummer  </div>{%endif%}
		<p><label for="id_phone">Phone:{{form.phone}}</p>
		
		{% if form.isWorker.errors %}  <div class="error"> sæt flurben her</div>{%endif%}
		<p><label for="id_isWorker">Vil du registrere dig selv som en der tilbyder både arbjede og arbjedstjenester:</label> {{form.isWorker}}</p> 
		{% if form.keyword.errors %}  <div class="error"> Hold "Ctrl" (eller "Æbletasten" på Mac) nede for at vælge mere end en.</div>{%endif%}
		<p><label for="keyword"> Hvis du leder efter job, så kan du vælge hvilken jobtype du leder efter</label></br>
		{{form.keyword}}</p>
	
				
		
		{% if form.errors %} <div class="error">{{form.errors}} Vær at venlig at indtaste korrekt information</div> {%endif%}
		<input type="submit" alt="register", value="register">
	</form>
</div>
{% endblock%}